### PR TITLE
add support for vscode

### PR DESCRIPTION
**Pull request by colemickens**

### CODE REVIEW

**Review by 318h7 — CHANGES_REQUESTED** [review]
Please add test and update README.

**Review by 318h7 — COMMENTED** [review]
Also, add the format to the export in the `lib/index.js`

**Comment by 318h7** [comment]
Given another thought, I think this feature is outside the scope of this package.
The name itself implies that it's a terminal color tool, and vscode, as we know it is a IDE.
If you just want to mount themes from [xresources themes repo](https://github.com/logico-dev/Xresources-themes)  or terrminal.sexy, you should look into [base16](https://github.com/chriskempson/base16). The project collects all possible color themes in a format that is actually used by the IDE (and terminal.sexy as well). I've never tried it myself, but I imagine it should be easy to mount a theme from there.

**Comment by colemickens** [comment]
This PR, though poorly titled, was specifically for the integrated terminal in VSCode. As it is, I no longer use this, so I'm going to just close this.

**Pull request closed without merging**
